import os
import logging
from pathlib import Path
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import cm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, HRFlowable
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT

logger = logging.getLogger(__name__)

NAVY       = colors.HexColor("#0A1F44")
LIGHT_GRAY = colors.HexColor("#F4F6F8")
MID_GRAY   = colors.HexColor("#6B7280")
WHITE      = colors.white

FOOTER_DISCLAIMER = (
    "Tendrai assists in documentation preparation and submission support. "
    "Final responsibility remains with the bidder."
)

# Try to find logo — check multiple locations
_LOGO_CANDIDATES = [
    "/home/claude/tendrai/frontend/public/logo.png",
    "/home/claude/tendrai/frontend/src/assets/logo.png",
    "./logo.png",
]
LOGO_PATH = next((p for p in _LOGO_CANDIDATES if os.path.exists(p)), None)


def _styles() -> dict:
    return {
        "h1": ParagraphStyle("h1", fontName="Helvetica-Bold", fontSize=16,
                              textColor=NAVY, spaceAfter=10),
        "h2": ParagraphStyle("h2", fontName="Helvetica-Bold", fontSize=12,
                              textColor=NAVY, spaceAfter=8),
        "body": ParagraphStyle("body", fontName="Helvetica", fontSize=10,
                               textColor=colors.black, spaceAfter=6, leading=15),
        "small": ParagraphStyle("small", fontName="Helvetica", fontSize=8,
                                textColor=MID_GRAY, leading=11),
        "footer": ParagraphStyle("footer", fontName="Helvetica-Oblique", fontSize=7,
                                 textColor=MID_GRAY, alignment=TA_CENTER),
    }


def _footer_canvas(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica-Oblique", 7)
    canvas.setFillColor(MID_GRAY)
    w = A4[0]
    canvas.drawCentredString(w / 2, 1.4 * cm, FOOTER_DISCLAIMER)
    canvas.drawCentredString(
        w / 2, 0.9 * cm,
        f"Generated by TendrAI  |  {datetime.now().strftime('%d %B %Y  %H:%M')}  |  Page {doc.page}"
    )
    canvas.restoreState()


def _build_letterhead(story: list, styles: dict, doc_title: str, tender_title: str = ""):
    """Shared letterhead: logo + title + divider."""
    # Logo row
    if LOGO_PATH:
        try:
            from reportlab.platypus import Image
            logo_img = Image(LOGO_PATH, width=2.8 * cm, height=1.9 * cm)
            header_data = [[
                logo_img,
                Paragraph(
                    "<b>TENDRAI</b><br/>AI-Powered Tender Management Platform<br/>"
                    f"<font color='#6B7280' size='8'>{datetime.now().strftime('%d %B %Y')}</font>",
                    styles["body"]
                )
            ]]
            ht = Table(header_data, colWidths=[3.5 * cm, 13.5 * cm])
            ht.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "MIDDLE")]))
            story.append(ht)
        except Exception as e:
            logger.warning(f"Logo render failed: {e}")
            story.append(Paragraph("<b>TENDRAI</b> | AI-Powered Tender Management", styles["h1"]))
    else:
        story.append(Paragraph("<b>TENDRAI</b> | AI-Powered Tender Management", styles["h1"]))

    story.append(HRFlowable(width="100%", thickness=2, color=NAVY, spaceAfter=6))
    story.append(Paragraph(doc_title, styles["h1"]))
    if tender_title:
        story.append(Paragraph(tender_title, styles["h2"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=MID_GRAY, spaceAfter=10))


def _table_style(has_header=True):
    style = [
        ("FONTSIZE",    (0, 0), (-1, -1), 9),
        ("GRID",        (0, 0), (-1, -1), 0.4, colors.HexColor("#D1D5DB")),
        ("PADDING",     (0, 0), (-1, -1), 6),
        ("VALIGN",      (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [WHITE, LIGHT_GRAY]),
    ]
    if has_header:
        style += [
            ("BACKGROUND", (0, 0), (-1, 0), NAVY),
            ("TEXTCOLOR",  (0, 0), (-1, 0), WHITE),
            ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
        ]
    return TableStyle(style)


def generate_cover_letter(output_path: str, tender_data: dict, company_name: str = "Bidder Company") -> str:
    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        topMargin=2 * cm, bottomMargin=3 * cm,
        leftMargin=2.5 * cm, rightMargin=2.5 * cm
    )
    styles = _styles()
    story = []

    _build_letterhead(story, styles, "COVER LETTER", tender_data.get("title", ""))
    story.append(Spacer(1, 0.4 * cm))

    story.append(Paragraph(f"Date: <b>{datetime.now().strftime('%d %B %Y')}</b>", styles["body"]))
    story.append(Spacer(1, 0.3 * cm))
    story.append(Paragraph("To,<br/>The Tender Inviting Authority,<br/>Concerned Government Department", styles["body"]))
    story.append(Spacer(1, 0.4 * cm))
    story.append(Paragraph("<b>Subject: Submission of Tender Bid</b>", styles["h2"]))
    story.append(Spacer(1, 0.3 * cm))

    body = f"""
Dear Sir / Madam,<br/><br/>
We, <b>{company_name}</b>, hereby submit our tender application for the above-referenced tender
with reference to your Notice Inviting Tender (NIT).<br/><br/>
We confirm compliance with all eligibility and technical criteria as specified in the tender document.
All required certificates and supporting documents are enclosed herewith.<br/><br/>
<b>Key Compliance Summary:</b><br/>
Eligibility: {tender_data.get('eligibility', 'As per tender requirements')}<br/>
Minimum Turnover: {tender_data.get('turnover', 'As specified')}<br/>
Experience: {tender_data.get('experience', 'As specified')}<br/>
EMD: {tender_data.get('emd', 'Enclosed as per requirements')}<br/><br/>
We affirm that all information furnished is true and correct. We accept all terms and conditions of the tender document.<br/><br/>
Yours faithfully,<br/><br/><br/>
<b>{company_name}</b><br/>
Authorized Signatory &amp; Seal<br/>
Date: {datetime.now().strftime('%d %B %Y')}
"""
    story.append(Paragraph(body, styles["body"]))
    doc.build(story, onFirstPage=_footer_canvas, onLaterPages=_footer_canvas)
    return output_path


def generate_compliance_checklist(output_path: str, tender_data: dict) -> str:
    doc = SimpleDocTemplate(
        output_path, pagesize=A4,
        topMargin=2 * cm, bottomMargin=3 * cm,
        leftMargin=2.5 * cm, rightMargin=2.5 * cm
    )
    styles = _styles()
    story = []

    _build_letterhead(story, styles, "COMPLIANCE CHECKLIST")

    # ── Certificates ──
    story.append(Paragraph("1. Required Certificates & Documents", styles["h2"]))
    certs = tender_data.get("certificates_required", [])
    data = [["#", "Certificate / Document", "Status", "Reference No."]]
    for i, c in enumerate(certs, 1):
        data.append([str(i), c, "☐  Enclosed", ""])
    t = Table(data, colWidths=[0.8*cm, 9*cm, 3*cm, 4*cm])
    t.setStyle(_table_style())
    story.append(t)
    story.append(Spacer(1, 0.4 * cm))

    # ── Technical Requirements ──
    story.append(Paragraph("2. Technical Compliance", styles["h2"]))
    tech = tender_data.get("technical_requirements", [])
    data2 = [["#", "Requirement", "Compliant"]]
    for i, r in enumerate(tech, 1):
        data2.append([str(i), r, "☐  Yes   ☐  No"])
    t2 = Table(data2, colWidths=[0.8*cm, 12*cm, 4*cm])
    t2.setStyle(_table_style())
    story.append(t2)
    story.append(Spacer(1, 0.4 * cm))

    # ── Important Dates ──
    story.append(Paragraph("3. Important Dates", styles["h2"]))
    dates = tender_data.get("important_dates", [])
    data3 = [["Event", "Date", "Status"]]
    for d in dates:
        data3.append([d.get("event", ""), d.get("date", ""), "☐  Noted"])
    t3 = Table(data3, colWidths=[9*cm, 4*cm, 4*cm])
    t3.setStyle(_table_style())
    story.append(t3)
    story.append(Spacer(1, 0.4 * cm))

    # ── Financial ──
    story.append(Paragraph("4. Financial Compliance", styles["h2"]))
    fin_data = [
        ["Parameter", "Requirement", "Compliance"],
        ["EMD",       tender_data.get("emd", "—"),      "☐  Enclosed"],
        ["Turnover",  tender_data.get("turnover", "—"),  "☐  Certificate Enclosed"],
        ["Experience",tender_data.get("experience", "—"),"☐  Documents Enclosed"],
    ]
    t4 = Table(fin_data, colWidths=[4*cm, 9*cm, 4*cm])
    t4.setStyle(_table_style())
    story.append(t4)

    doc.build(story, onFirstPage=_footer_canvas, onLaterPages=_footer_canvas)
    return output_path


def generate_summary_txt(output_path: str, tender_data: dict, tender_title: str = "") -> str:
    sep = "=" * 62
    lines = [
        sep,
        "  TENDRAI — TENDER SUMMARY REPORT",
        sep,
        f"  Tender   : {tender_title}",
        f"  Generated: {datetime.now().strftime('%d %B %Y  %H:%M UTC')}",
        sep,
        "",
        "ELIGIBILITY",
        "-" * 40,
        tender_data.get("eligibility", "Not specified"),
        "",
        "EMD REQUIREMENT",
        "-" * 40,
        tender_data.get("emd", "Not specified"),
        "",
        "TURNOVER REQUIREMENT",
        "-" * 40,
        tender_data.get("turnover", "Not specified"),
        "",
        "EXPERIENCE REQUIREMENT",
        "-" * 40,
        tender_data.get("experience", "Not specified"),
        "",
        "CERTIFICATES REQUIRED",
        "-" * 40,
    ]
    for c in tender_data.get("certificates_required", []):
        lines.append(f"  •  {c}")

    lines += ["", "IMPORTANT DATES", "-" * 40]
    for d in tender_data.get("important_dates", []):
        lines.append(f"  {d.get('event',''):<35}  {d.get('date','')}")

    lines += ["", "TECHNICAL REQUIREMENTS", "-" * 40]
    for r in tender_data.get("technical_requirements", []):
        lines.append(f"  •  {r}")

    lines += ["", sep, f"  {FOOTER_DISCLAIMER}", sep]

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    return output_path
